### ISSUE TITLE
Issue using expire option

### ISSUE THREAD

**Issue by MarkL4YG** [reactivestack/cookies#108]
Hey there, whenever I try to set a cookie using the expire option the cookie is never set and execution seems to halt as the lines afterwards never get called. No errors or warnings whatsoever.

* ReactJS 4
* Chrome: ``60.0.3112.113``
* universal-cookie: ``2.1.0``  

This is a snippet of the code I use:  
```javascript
let _Cookies = new Cookies();

let d = new Date();
d.setTime(d.getTime() + (64 * 1000 * 60 * 60));
let dateString = '' + d.toUTCString();
console.log(dateString); // e.g. "Tue, 26 Sep 2017 05:10:23 GMT"
_Cookies.set("cookie-name", JSON.stringify(this.getCookie()), {
  path: '/',
  expires: dateString
});
console.log("Cookies saved"); // Never called
```  
If I omit the expires option the cookie is successfully set and the script is executed as normal.

**Comment by MarkL4YG** [comment]
Apparently ``expires`` takes the ``Date`` and no string.  

Some warning or explicit documentation may be helpful instead of halting execution though.

**Comment by awreese** [comment]
Wow, this little detail is extremely frustrating since it's not documented **anywhere** really.  After digging a bit it seems the offending culprit is the cookie.js module, but at least it's readme explains the expires options requires a `Date` object, but it'd be nice to at least get a useful error message.  It's codebase seems to be a little stale as it's only recent modifications are npm version bumps and slight revisions to the readme.

It should, IMO, take a date string and compile nicely so long as the string follows any allowed date format string recognized by JS date functions, especially since it's still vanilla JS under the hood and reduces down to a string anyway.  

A work-around I'm using is the Moment.js module to work with dates a little easier and passing it's string into a new date object.

```js
// create expiration date object that expires 15 minutes from now
cookies.set('COOKIE', '15 minute cookie', { expires: new Date(moment().add(15, 'm').format()) });
```

**Comment by MarkL4YG** [comment]
Seconded. Moment.js seems quite neat actually.

**Comment by bedjiken** [comment]
@awreese your solution is good but it adds moment dependency, it might be good for people using moment in their project.

const timestamp = new Date().getTime();
const expire = timestamp + (60 * 60 * 24 * 1000 * 3)

Note: 60 minutes * 60 seconds * 24 hours * 1000 (for milliseconds) * 3 days

And then convert the expire in Date;
const expireDate = new Date(expire)

cookies.set('COOKIE', '3 days', { expires: expireDate });

**Comment by bedjiken** [comment]
`code here`
