### ISSUE TITLE
Error in setCookie

### ISSUE THREAD

**Issue by Sagaryalioe** [reactivestack/cookies#150]
It was working just few minutes ago and now the cookies.set() is not working? What is the reason?

**Comment by Sagaryalioe** [comment]
Sorry for not elaborating the question, I posted the issue ahead presuming it might be the package problem when it suddenly stopped working without any change in our code. But during our debugging process, it is found that the size of the cookie exceeded the limit and that was the reason of error. What is the standard process for storing such large data in cookies? By the way thanks for your response.

**Comment by eXon** [comment]
Hi @Sagaryalioe 

Cookies should not exceed 4K (including name and all the formatting). You are probably safe if you keep it under 4000 bytes because you still have 96 bytes for the name and options. See https://stackoverflow.com/a/4604212/1692356

However, keep in mind that your cookies are sent with all your HTTP requests. You might want to use the localStorage instead because the limit is 5 MB: https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage

However, with the local storage you would not be able to do server-side rendering if you need it.

I hope that helps!

**Comment by Sagaryalioe** [comment]
Thanks for the suggestion.
