### ISSUE TITLE
Unable to set cookie with domain parameter using Universal-Cookie in ReactJS

### ISSUE THREAD

**Issue by schakraborty2050** [reactivestack/cookies#170]
My react app is on localhost, APIs is on AWS lambda I want to set cookie for the APIs to pass user authentication token on each API call. I am using universal-cookie plugin it is working fine without domain parameter it is taking localhost by default and passing cookie back to all localhost requests, but when I am passing aws url in domain parameter cookie not being saved.

Here is the code I am using to set domain

cookies.set('cookieAuth', res.data.auth_token, { path: '/', expires: expOn, domain: '.amazonaws.com'});

**Comment by eXon** [comment]
For a lot of good security reasons, you cannot set cookies on any domain. There is two ways you can handle that:

1. You manage your cookies server-side completely and use `credentials` with fetch or `withCredentials` with XHR so that every next calls include them. Probably not your best option.

2. You manage your cookie client-side only and send your `auth_token` through a header or something like that.

Hope it helps

**Comment by schakraborty2050** [comment]
thanks.
