### ISSUE TITLE
useCookies hook always compares dependencies with initial cookies

### ISSUE THREAD

**Issue by lkarmelo** [reactivestack/cookies#210]
In useCookies.tsx
```javascript
 const cookies = useContext(CookiesContext);
```
cookies object is always the same and therefore in useEffect callback in this line
```javascript
if (shouldUpdate(dependencies || null, newCookies, allCookies)) {
     setCookies(cookies.getAll());
}
```
allCookies are always initial cookies due to closure.

**Comment by eXon** [comment]
You are right, I'm still new to hooks 😆 . I'll add a test with 2 changes on the cookie and use a ref to track the old cookies.

**Comment by eXon** [comment]
Hey @lkarmelo 

I just wanted to make sure it wasn't because of my lack of comprehension of React hooks so I've added a test to cover your use case.

`allCookies` is updated every time the cookies change. That means if it changes twice, the flow will be:

1. first render, everything is as expected
2. a cookie is changed, that means we update the cookies state if any dependency has changed.
3. a cookie changed again, that means we update the cookie state if the value changed compared to the previous saved state

Do you have a specific case it would not work?

**Comment by lkarmelo** [comment]
@eXon 
I have opened PR with test case concerning this issue. It only appears if the cookie value is changed back to initial one and not if it changes multiple times to any other value.

The reason is useEffect not calling callback function because of [cookies] specified in dependency array. "cookies" variable always contains reference to the same object and each rerender it gets compared to itself. And if callback inside useEffect never gets called againg, the onChange function (line 22) is also never recreated after first render and it gets closed over scope of first render, containing initial allCookies value.

If you debug onChange function, you will see that allCookies always contains initial value. Your new test case is passing because initial value gets compared with 'mean lean cat Suki' value and then the initial value is also compared with 'good old Yuki', while it should compare 'mean lean cat Suki' with 'good old Yuki' after second change.

The quick fix is to add allCookies to dependencies arrays in useEffect as second argument, making it
```javascript
useEffect(
    () => {/*...*/},
    [cookies, allCookies]
)
```
but then event listener will be removed and created again after each rerender after cookie value change. I will try to come up with better approach and send PR.
