### ISSUE TITLE
Why cannot parse cookie as string on client?

### ISSUE THREAD

**Issue by nghiepit** [reactivestack/cookies#244]
Hi all,

I don't know why my cookies cannot working on client?

Example:

```js
import Cookies from 'universal-cookie';

console.log(new Cookies('foo=bar').get('foo'));
```
In browser will console.log `undefined`. Why? why? 
Is there a bug or specification?

**Comment by eXon** [comment]
You cannot specify the cookies because you are in a browser environment and it is using the browser's cookies instead. If you really need to do that on the browser, you need to set `cookies.HAS_DOCUMENT_COOKIE = false` just like that:

```
const cookies = new Cookies('foo=bar');
cookies.HAS_DOCUMENT_COOKIE = false;
const test = cookies.get('foo');
expect(test).toBe('bar');
```

It is not documented because this is not typical. If you want to read cookies from a string, it might be easier to use the [cookie](https://www.npmjs.com/package/cookie) library instead.
