### ISSUE TITLE
Understanding the API of useCookies

### ISSUE THREAD

**Issue by karland** [reactivestack/cookies#258]
The API of `useCookies` is defined as:

```JSX
const [cookies, setCookie] = useCookies(["someCookie"])
```
Shouldn't that rather be:

```JSX
const {cookies, setCookie} = useCookies(["someCookie"])
```

My reasoning is the following:

1. not in all cases `cookies` is needed. If not one will get a warning. In my suggestion, I could do `const {setCookie} = useCookies(["someCookie"])`. I know I can avoid the error message with: 

    ```JSX
    const setCookie = useCookies(["someCookie"])[1]
    ```

1. the API looks like useState, however, `setCookie` is not setting `cookies` like a state-variable.

Maybe, however, I am completely wrong? Other than that, thanks for this awesome library.

**Comment by coreyleelarson** [comment]
@karland - You could do `[, setCookie] = useCookies(["someCookie"])`. It's not pretty, IMO, but it works.

**Comment by LauraBeatris** [comment]
I think that issue here is not with the API but rather than this, related to the implementation styles. 

The API works there are some downsides:

1. It's easier to restructure just the necessary data from an object than an array:

Example: 
```
const { setCookie } = useCookies(["someCookie"])

const [, setCookie ] = useCookies(["someCookie"])
```

2. The variables names can be easily changed across the codebase and lead to inconsistent issues 

module1.tsx
``
const [cookiesData, setCookiesData] = useCookies(["someCookie"])
``

module2.tsx
``
const [cookies, setCookies] = useCookies(["someCookie"])
``

Although, change the return result to be an object instead of an array would be a breaking change and I don't think it's worth releasing a major version for it.
