### ISSUE TITLE
httpOnly Option not working in react?

### ISSUE THREAD

**Issue by sunggun1** [reactivestack/cookies#273]
My code: 
function login(event)=>{
const {cookies} = this.props;
login(email)
.then(login_response) => {
cookies.set('refreshtoken',login_response.data.token,{httpOnly:true, sameSite:true});
}.catch(login_error)=>{
}
}

cookies.set with httpOnly option doesn't work 

If Google oAuth login succeed , then I get a jwt token from server. I want to make it as a httpOnly cookie.
Does it work in react? I saw a post that making a httpOnly cookie in frontend is impossible.
That's the reason why I can't make httpOnly cookie?

**Comment by MeRahulAhire** [comment]
I'm having same issue here

**Comment by eXon** [comment]
@MeRahulAhire httpOnly cookie means the cookie cannot be set or read from the browser, only by the server. It means that if you try to set/get one, it would be ignored.

**Comment by MeRahulAhire** [comment]
Thanks @eXon for clearing that. I'd suggest to mention this fact in your docs as well since there isn't clear cut explanation on this topic. But I had an doubt that If I cant access `httpOnly` cookie then, how do I send it with authorization header and especially if I'm storing refresh and access token in cookie then I at least need to access the refresh token in order to replace the expired access token. Im building protected route in React with JWT and cookie.

**Comment by eXon** [comment]
Yes I will add it on the doc, I should have done that a long time ago it's a common mistake. 

It boils down to how cookies work. When you set a cookie, it will be included in every requests made to the server within the scope of the cookie (domain, path, etc.). When the cookie is httpOnly, you cannot retrieve it with the browser and cannot send it in the Authorization header as a bearer token. However, the server can instead read the cookie because they are all automatically sent. 

You need to be aware that if you are calling an API from the browser, you need to make sure the credentials option is set to the correct value so that they send the cookies, they are not sent by default. If you're calling an API on the same domain as the website, you can set it to same-origin and if it's a different domain you can set it to include.

If you still want to use the header, be careful where you save the cookie. There is no safe place, non-httpOnly cookies and localStorage are considered widely unsecure.

**Comment by MeRahulAhire** [comment]
so to use the httponly cookie should I use your express-universal-cookies library on server side as its cant be done on browser? If possible could you please suggest me some resource that deals with httpOnly cookies, JWT and react protected routes if you have came across any. I'm stuck on it since last 4 days

**Comment by eXon** [comment]
@MeRahulAhire If you're using httpOnly cookies, it would be most likely simplier to manage all of that server-side only and use the [cookier parser middlware](http://expressjs.com/en/resources/middleware/cookie-parser.html). If you're looking for an authentication system, you can also use [passport.js](http://www.passportjs.org/). If you Google a little bit you will find a ton of tutorials on how to use it.
