### ISSUE TITLE
not work on iphone

### ISSUE THREAD

**Issue by ofirk12** [reactivestack/cookies#55]
i have strange problem i am use react-cookie and its work only in android .. i am using  chrom in iphone and its not work , i am using chrom in android its work , what can be the problem ?

**Comment by eXon** [comment]
Do you have a way to replicate the problem? What's your iOS version? Are you in private mode?

**Comment by carterwarrengravitas** [comment]
iOS 10-10.1 doesn't support cookie.load(). Haven't tested in 10.2 but due to this huge issue my site (which relies heavily on cookies) can't properly display pages. (Android seems fine as far as we've tested.)

Between this and the subdomain issue, I have to pull this plugin from the site unfortunately. Doing it by hand now.

**Comment by eXon** [comment]
It looks like iPhone disable cookies by default. Maybe we should do a fallback on sessionStorage/localStorage. The other way around makes more sense to me.

Have you tried to enable the cookies? (i know your user will most likely not do that, but just to be sure this is the problem)

**Comment by eXon** [comment]
@carterwarrengravitas FYI the subdomain issue is fixed. It was just a documentation issue. The correct syntax is fixed on the readme. (short answer: don't put the protocol, just the domain, and start with a dot instead of * for the wildcard)
