### ISSUE TITLE
Expressjs server side cookie prefixed with j/s

### ISSUE THREAD

**Issue by Exomnius** [reactivestack/cookies#62]
I have a reactjs application that uses SSR and runs on an Expressjs node server. For my current case I need to set a cookie during the SSR and read in on the client-side in the browser.

The issue is that whenever I set a cookie with a value that contains an object during SSR, the cookie value will be prefixed with a j:. When I try to read the cookie on the client-side, I need to perform extra parsing.

The reason for this is that whenever I set a cookie server-side, Expressjs prefixes the cookie with j: if it is an object and s: if it is a signed cookie. 

Is it possible to take the prefixes into account when loading the cookie client-side?

Regards
Cornel Janssen

**Comment by macdonaldr93** [comment]
I'm wondering about this too.

**Comment by eXon** [comment]
I'm not sure why express prefix those cookies. Do you have any documentation on why it is doing that? 

I suggest that you define a variable to know if you are client or server side within your code.

**Comment by djgrant** [comment]
@eXon I haven't checked but it looks like cookies are being set on `res` without first being stringified https://github.com/reactivestack/cookies/blob/master/src/cookie.js#L74

**Comment by ZsoltMaslanyi** [comment]
@djgrant is right. Passing the value to be stored through JSON.stringify resolved the problem.

**Comment by YPCrumble** [comment]
@eXon [here's the code](https://github.com/expressjs/express/blob/master/lib/response.js#L836) in Express where they're prefixing the "j:" to signify that the cookie is JSON. [They say it's a convenience](https://github.com/expressjs/express/issues/2815) to allow setting objects as cookies directly in ExpressJS.

What I would suggest is to reopen this issue, or perhaps reopen it in universal-cookie-express, as it appears that [universal-cookie-express middleware doesn't take this into account either](https://github.com/reactivestack/cookies/blob/master/packages/universal-cookie-express/src/index.ts#L21).

I would love to see one of these libraries check for the "j:" before loading the cookie because without this check it seems that I can't very easily switch to these libraries without writing the code to stripe the "j:" from any cookie before passing it to either universal-cookie or universal-cookies-middleware.

My preference would be to reopen here and check for the "j:" so that this library can be used immediately on apps that have used regular express cookies in the past. This would also handle the issue in universal-cookies-middleware automatically.

I'd be happy to work on the PR - let me know if that would be welcomed and whether you have any suggestions/concerns?

Also, thank you for maintaining this great repo!

**Comment by eXon** [comment]
@YPCrumble I'm very reluctant to add anything express-specific. Especially because it is not in the RFC. However, express makes it impossible to

**Comment by eXon** [comment]
In the next version, `j:` will be automatically removed when deserializing so that it stay consistent with how it works on the browser and express.

**Comment by YPCrumble** [comment]
@eXon thank you so much for this! I have a question - I'm trying to deploy the GitHub version of this repo in my project but it isn't letting me do that. For instance, trying:

    "universal-cookie": "reactivestack/cookies#40db1eb"

...returns the error:

> error Can't add "universal-cookie": invalid package version undefined.

This repo holds a few different packages in one place - do you know a way to deploy the latest version of `universal-cookie`? Or if now would you be willing to deploy a 3.0.5 release to include this change?

Thanks again!
