### ISSUE TITLE
Isomorphic cookies react-cookie v2

### ISSUE THREAD

**Issue by MitchWeiss** [reactivestack/cookies#83]
Is it possible to get/set a cookie with react-cookie v2 either server side or client side without wrapping the component with `withCookies`?

I don't want to have to wrap every component which access cookies in a HOC. Also, I don't see how I could access cookies in a place such as an `onEnter` hook in `React-Router` eg to set a cookie as I enter a route. 

An example `onEnter` hook:

```
export const loadIntoCookie = (store) => {
  return (nextState, replace, cb) => {
      store.dispatch(myAction)
          .then(res => {
              cookie.save("key", res.data.value)
              cb();
          })
  }
}
```

Maybe I am approaching this wrong! Any help is greatly appreciated.

**Comment by mgreer** [comment]
I'm also puzzled by how to solve this use case, which is fairly simple in the 1.x branch. Seems like the cookies need to be passed from the component?

**Comment by eXon** [comment]
The reason behind react-cookie v2 is to make sure when doing server-rendering, you can't steal the cookies from another user because of async issues. Your cookies are safe within your `renderToString` and any other async jobs you might have in between.

If you wish to access the `cookies` object without React, the easiest way is to dispatch it within your Redux store. That way you don't need withCookies everywhere.

If you don't care about server-rendering and just want the old way, you can use `universal-cookie`. But if you do server-rendering it is not a good idea.

**Comment by sebmor** [comment]
I have to be honest I am kind of sad the way you rewrote the package using HoC. 1.x while not perfect, was much more elegant. Perhaps we can keep supporting it similar to react-router does 3.x

**Comment by eXon** [comment]
@sebmor The complete rewrite was necessary for async server rendering or your cookies will be messed up between your users.

I do agree a simplier API is better if you don't care. It is the purpose of univetsal-cookie. Their is a lunk in the doc you should check it out. It's almost the same as 1.0.

Now react-cookie is a little bit more react-like and universal-cookie is there for a simplier javascript version. I'll try to clarify that on the doc.
