### ISSUE TITLE
(question) Breaking changes

### ISSUE THREAD

**Issue by gabrielrtakeda** [reactivestack/cookies#89]
Hey guys, as the repo do not have a changelog file, I need to ask if the upgrade to v2 have some breaking changes that I need to care about when migrating from v1.

Thanks

**Comment by eXon** [comment]
Hi @gabrielrtakeda 

The library has changed dramatically on v2.0. There is no CHANGELOG file because it is almost as a new library.

If you wish to use a JavaScript API without React, you can use `universal-cookie`. The migration should be painless just by reading the doc.

If you care about React and async server-rendering (doing multiple at the same time), I highly recommend you check out the new `react-cookie`. However, the change is dramatic.

**Comment by johhansantana** [comment]
I just noticed this, the library looks completely revamped, you should lock your old apps using the older version of this `react-cookies` and not update it to v2.

**Comment by oyeanuj** [comment]
Also, came here for the same question. 

@eXon Can we add this to the README and/or start a Changelog (since I noticed that even with v2, the library has gone to 2.1)?

Grateful for your work on this, so just a suggestion to improve the DX. Thank you!

**Comment by brandondurham** [comment]
It really leaves your users in the dark if you don’t offer some kind of documentation around migrating or even a README mention that the library is so different that an actual migration isn’t possible. Something they can locate outside of a Github issue.
